xgboost:
  n_estimators: 300
  learning_rate: 0.05
  max_depth: 5
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

randomforest:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 2
  random_state: 42
